--1. select distinct(replacement_cost) from film
--2. select count(distinct(replacement_cost)) from film
--3. select count(distinct(title)) from film where title like'T%' and rating='G'
--4. select count(distinct(country)) from country where Length(country)=5
--5. select count(distinct(city)) from city where city ilike '%r'
